// front/src/components/HabitDay.svelte
import * as Popover from '@radix-ui/react-popover'
import { ProgressBar } from './ProgressBar'
import clsx from 'clsx'
import dayjs from 'dayjs';
import { HabitsList } from './HabitsList';
import { useState } from 'react';

// interface HabitProps {
//     completed: number
// }

interface HabitDayProps {
    date: Date
    defaultCompleted?: number
    amount?: number
}

export const HabitDay = ({ defaultCompleted = 0, amount = 0, date }: HabitDayProps) => {
    const [completed, setCompleted] = useState(defaultCompleted)

    const completedPercentage = amount > 0 ? Math.round((completed / amount) * 100) : 0
    const dayAndMonth = dayjs(date).format('DD/MM')
    const dayOfWeek = dayjs(date).format('dddd')

    const today = dayjs().startOf('day').toDate()
    const isToday = dayjs(date).isSame(today)

    const handleCompletedChanged = (completed: number) => {
        setCompleted(completed)
    }
    return (
        <Popover.Root>
            <Popover.Trigger className={clsx('w-10 h-10 border-2  rounded-lg transition-colors focus:outline-none focus:ring-2 focus:ring-violet-600 focus:ring-offset-2 focus:ring-offset-background', {
                ['bg-violet-500 border-violet-400']: completedPercentage >= 80,
                ['bg-violet-600 border-violet-500']: completedPercentage < 80 && completedPercentage >= 60,
                ['bg-violet-700 border-violet-500']: completedPercentage < 60 && completedPercentage >= 40,
                ['bg-violet-800 border-violet-600']: completedPercentage < 40 && completedPercentage >= 20,
                ['bg-violet-900 border-violet-700']: completedPercentage < 20 && completedPercentage >= 1,
                ['bg-zinc-900 border-zinc-800']: completedPercentage == 0,
                ['border-zinc-500 border-4 ']: isToday
            })} />

            <Popover.Portal>
                <Popover.Content
                    className='min-w-[320px] p-6 rounded-2xl bg-zinc-900 flex flex-col'
                >
                    <span className='font-semibold text-zinc-400'>{dayOfWeek}</span>
                    <span className='mt-1 font-extrabold leading-tight text-3xl'>{dayAndMonth}</span>

                    <ProgressBar progress={completedPercentage} />

                    <HabitsList date={date} onCompletedChanged={handleCompletedChanged} />

                    <Popover.Arrow height={8} width={16} className='fill-zinc-900' />
                </Popover.Content>
            </Popover.Portal>
        </Popover.Root >
    )
}

// web/src/components/HabitDay.tsx
import * as Popover from '@radix-ui/react-popover'
import { ProgressBar } from './ProgressBar'
import clsx from 'clsx'

// interface HabitProps {
//     completed: number
// }
interface HabitDayProps {
    completed: number
    amount: number
}

export const HabitDay = ({ completed, amount }: HabitDayProps) => {

    const completedPercentage = Math.round((completed / amount) * 100)

    return (
        <Popover.Root>
            <Popover.Trigger className={clsx('w-10 h-10 border-2  rounded-lg', {
                'bg-violet-500 border-violet-400': completedPercentage >= 80,
                'bg-violet-600 border-violet-500': completedPercentage < 80 && completedPercentage >= 60,
                'bg-violet-700 border-violet-600': completedPercentage < 60 && completedPercentage >= 40,
                'bg-violet-800 border-violet-700': completedPercentage < 40 && completedPercentage >= 20,
                'bg-violet-900 border-violet-800': completedPercentage < 20 && completedPercentage >= 1,
                'bg-zinc-900 border-zinc-800': completedPercentage == 0
            })} />

            <Popover.Portal>
                <Popover.Content
                    className='min-w-[320px] p-6 rounded-2xl bg-zinc-900 flex flex-col'
                >
                    <span className='font-semibold text-zinc-400'>Segunda-feira</span>
                    <span className='mt-1 font-extrabold leading-tight text-3xl'>18/01</span>

                    <ProgressBar progress={completedPercentage} />

                    <Popover.Arrow height={8} width={16} className='fill-zinc-900' />
                </Popover.Content>
            </Popover.Portal>
        </Popover.Root >
    )
}
